### ISSUE TITLE
Learning curves in IB

### ISSUE THREAD

**Issue by joseluperez1999** [polixir/NeoRL#9]
Hi,

i am executing benchmark scripts with IB datasets and I am not getting any results. The picture corresponds to the running of BCQ with the IB-Low-100 dataset. Each 10 training epochs I run 100 validation episodes and obtain its mean reward, the result is an horizontal line, no learning takes place.

Thank you for all you answers!

![ib_benchmark_training_curve_example](https://user-images.githubusercontent.com/90961222/217589490-1196dc9a-d8f0-4b44-a6da-07d56ec375e5.jpg)

**Comment by mzktbyjc2016** [comment]
Hi, we run BCQ with IB-Low-100 and found the same trend, even in other level of the IB datasets. 

After checking the code and the internal output of the policy, we found the change of the policy (derived from the Q-net where the action is generated by VAE) in IB env is very slow. The latent z in VAE is clipped to (-0.5, 0.5) and sent to the decoder net, and finally activated by tanh. We found z are clipped to -0.5 or 0.5 for most of its dimensions, so that the output actions are nearly the same in the "early" training phase. Maybe the interval (-0.5, 0.5) is narrow and should be expanded on IB, currently, we just follow the originally BCQ implementation.
